services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:${WEB_PORT} manage:app
    volumes:
      - template_volume:/home/app/web/project/templates
    expose:
      - "${WEB_PORT}"
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    depends_on:
      - db
    networks:
      - flask-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEB_PORT}"]
      interval: 30s
      retries: 3
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - flask-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    links:
      - "db:pgsql-server"
    networks:
      - flask-network

  nginx:
    build: ./services/nginx
    volumes:
      - template_volume:/home/app/web/project/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"  
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - WEB_PORT=${WEB_PORT}
      - MY_DNS=${MY_DNS}
    depends_on:
      - web
    networks:
      - flask-network
    # Nginx configuration file to be used
    # Make sure to update nginx.conf to match the proxying setup

networks:
  flask-network:
    driver: bridge

volumes:
  postgres_data_prod:
  template_volume:
