###########
# DEV DOCKERFILE #
###########

FROM python:3.11.6-bullseye

# Set work directory
WORKDIR /home/app/web

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc git netcat

# Install dev tools (optional)
RUN pip install --upgrade pip

# Copy requirements
COPY requirements.txt ./
COPY requirements-dev.txt ./
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

# Copy project files
COPY . .

# Expose port for Flask
EXPOSE 5000

# Set environment variables for Flask dev
ENV FLASK_APP=project/__init__.py
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

# Use root for dev (for easy volume mounting)
USER root

# Default command: Flask dev server with reload
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
